data1 <- read.csv("01042018_MICE_standardized_instance_1.csv")
data2 <- read.csv("01042018_MICE_standardized_instance_4.csv")
data3 <- read.csv("01042018_MICE_standardized_instance_5.csv")
df_1 <- as.matrix(data1)
df_4 <- as.matrix(data2)
df_5 <- as.matrix(data3)
df_1T <- t(df_1)
df_4T <- t(df_4)
df_5T <- t(df_5)
matrices <- list(df_1T, df_4T, df_5T)
MOFAobject <- createMOFAobject(matrices)
ModelOptions <- getDefaultModelOpts(MOFAobject)
DirOptions <- list("dataDir" = "data", "outFile" = "data/test.hdf5")
TrainOptions <- getDefaultTrainOpts()
MOFAobject <- prepareMOFA(MOFAobject,DirOptions = DirOptions, ModelOptions = ModelOptions, TrainOptions = TrainOptions)
MOFAobject <- runMOFA(MOFAobject, DirOptions, mofaPath = "/anaconda/bin/mofa")
r2 <- calculateVarianceExplained(MOFAobject)
plotVarianceExplained(MOFAobject)
plotWeights(MOFAobject, view = "view_3", factor = 1)
plotTopWeights(MOFAobject, view = "view_3", factor = 1)
plotFactorScatter(MOFAobject, factors = 1:2, color_by = "TERT_wt", shape_by = "IDH_TERT_four")
plotWeightsHeatmap(MOFAobject, "view_3", factors=1:9, show_colnames=T)